/*
 * generated by Xtext 2.18.0.M3
 */
package no.ntnu.tdt4250


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class NginxRuntimeModule extends AbstractNginxRuntimeModule {
}
