/*
 * generated by Xtext 2.18.0.M3
 */
package no.ntnu.tdt4250


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class NginxStandaloneSetup extends NginxStandaloneSetupGenerated {

	def static void doSetup() {
		new NginxStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
