/*
 * generated by Xtext 2.18.0.M3
 */
package no.ntnu.tdt4250.ide

import com.google.inject.Guice
import no.ntnu.tdt4250.NginxRuntimeModule
import no.ntnu.tdt4250.NginxStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class NginxIdeSetup extends NginxStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new NginxRuntimeModule, new NginxIdeModule))
	}
	
}
