/*
 * generated by Xtext 2.18.0.M3
 */
package no.ntnu.tdt4250.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class NginxUiModule extends AbstractNginxUiModule {
}
