/*
 * generated by Xtext 2.18.0.M3
 */
package no.ntnu.tdt4250.ide.contentassist.antlr;

import no.ntnu.tdt4250.ide.contentassist.antlr.internal.InternalNginxParser;
import org.antlr.runtime.Token;
import org.antlr.runtime.TokenSource;
import org.eclipse.xtext.parser.antlr.AbstractIndentationTokenSource;

public class NginxTokenSource extends AbstractIndentationTokenSource {

	public NginxTokenSource(TokenSource delegate) {
		super(delegate);
	}

	@Override
	protected boolean shouldSplitTokenImpl(Token token) {
		return token.getType() == InternalNginxParser.RULE_WS;
	}

	@Override
	protected int getBeginTokenType() {
		return InternalNginxParser.RULE_BEGIN;
	}

	@Override
	protected int getEndTokenType() {
		return InternalNginxParser.RULE_END;
	}

	@Override
	protected boolean shouldEmitPendingEndTokens() {
		return false;
	}
}
